### ISSUE TITLE
app file does not found or accessible. 

### ISSUE THREAD

**Issue by chetanJTH** [omprakashchavan01/appium-pageobjectmodel#2]
- I had downloaded the project and trying to run with a few changes of devices in testNG.xml. but every time I run a project just keeps failing as it failed to find apk.
-  do I need to change anything in the current project?
-  check image, app is there.
![image](https://user-images.githubusercontent.com/48850556/136507981-4a7ef655-dc4a-441c-b25c-d5b39c007dd9.png)
![image](https://user-images.githubusercontent.com/48850556/136508123-3597a476-bf21-4817-abc1-fd992bd6498b.png)

**Comment by omprakashchavan01** [comment]
Are you enrolled to the course? Please report issues in the Q&A section of the course.
